# Generated by Django 5.0.6 on 2024-06-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_rename_user_artworks_user_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='artworks',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ10'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ3'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ4'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ5'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ6'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ7'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ8'),
        ),
        migrations.AddField(
            model_name='artworks',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='イメージ9'),
        ),
    ]
